---
# Gradle Resourse
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/ababup1192/concourse-spring.git

- name: gradle-project
  type: git
  source:
    uri: https://github.com/ababup1192/SpringMigrator.git

- name: report
  type: git
  source:
    uri: git@github.com:ababup1192/hello-spring-report.git
    private_key: {{github-private-key}}
    branch: master

- name: db
  type: docker-image
  source:
    repository: "mysql:5.7.17"

jobs:
- name: gradle-ci
  public: true
  plan:
  - get: gradle-project
    trigger: true
  - get: git-repo
  - get: report
  - get: db
  - task: gradle-test
    file: git-repo/gradle-test.yml
    ensure:
      do:
        - task: commit-report
          file: git-repo/commit-report.yml
        - put: report
          params:
            repository: updated-report
