---
# Gradle Resourse
resources:
- name: git-repo
  type: git
  source:
    uri: {{git-repo}}

- name: gradle-project
  type: git
  source:
    uri: {{target-uri}}

- name: report
  type: git
  source:
    uri: {{report-uri}}
    private_key: {{github-private-key}}
    branch: master

jobs:
- name: gradle-ci
  public: true
  plan:
  - aggregate:
      - get: gradle-project
        trigger: true
      - get: git-repo
      - get: report
  - task: gradle-test
    timeout: 20m
    privileged: true
    file: git-repo/gradle-test.yml
    ensure:
      do:
        - task: commit-report
          file: git-repo/commit-report.yml
        - put: report
          params:
            repository: updated-report
        - task: slack-notice
          file: git-repo/slack-notice.yml
